services:
  api-1: &api
    build:
      context: ./rinhaBackend2025Api
      dockerfile: Dockerfile
    hostname: api
    networks:
      - internal
      - payment-processor
    restart: always
    depends_on:
      - redis
    environment:
      #      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      #      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://host.docker.internal:8001
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://host.docker.internal:8002
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "130MB"

  api-2:
    <<: *api
    hostname: api-2

  nginx:
    image: nginx:1.28.0-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    networks:
      - payment-processor
      - internal
    depends_on:
      - api-1
      - api-2
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "15MB"

  redis:
    image: redis:8.0.3-alpine
    container_name: redis
    command: [ "redis-server", "--maxmemory", "75mb", "--maxmemory-policy", "allkeys-lru" ]
    networks:
      - internal
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "75MB"

networks:
  internal:
    driver: bridge
  payment-processor:
    external: true