version: "3.9"

services:
  consumer-1: &consumer
    image: gustavotbett/rinha-backend-2025-consumer:latest
    hostname: consumer-1
    networks:
      - internal
    environment:
#      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
#      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
       - PAYMENT_PROCESSOR_URL_DEFAULT=http://localhost:8001
       - PAYMENT_PROCESSOR_URL_FALLBACK=http://localhost:8002
    ports:
      - "9998:9998"
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "60MB"

  consumer-2:
    <<: *consumer
    hostname: consumer-2

  processor-1: &processor
    image: gustavotbett/rinha-backend-2025-processor:latest
    hostname: processor-1
    networks:
      - internal
    ports:
      - "9999"
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "60MB"

  processor-2:
    <<: *processor
    hostname: processor-2

  nginx:
    image: nginx:1.28.0-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    networks:
      - internal
    depends_on:
      - consumer-1
      - consumer-2
      - processor-1
      - processor-2
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "10MB"

  redis:
    image: redis:8.0.3-alpine
    container_name: redis
    command: [ "redis-server", "--maxmemory", "100mb", "--maxmemory-policy", "allkeys-lru" ]
    ports:
      - "16379:6379"
    networks:
      - internal
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "90MB"

  rabbitmq:
    image: rabbitmq:4.1.2-alpine
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - internal
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "50MB"

networks:
  internal:
    driver: bridge
